# SD config
sd_config:
  model_name: /home/roo/dream/wutr/SD-exp/stable-diffusion-v1-4 # path
  guidance_scale: 10.0
  scheduler_name: unipc
  frozen: True
  num_per_group: 4 # num prompts per group
  batch_size: 4 # num imgs per batch
  step_list: # will cover num_inference_steps
    - 10
    - 10
    - 10
    - 20
  num_inference_steps: 50
  negative_prompt: monochrome, lowres, bad anatomy, worst quality, low quality
  save_path: ./test_imgs

prompt_path: ./prompt/T2I_val.jsonl
step_describe:
  - visual_center
  - composition
  - artistic_style
  - color_tone