# style 1 艺术风格
s1t1: &s1t1 "你是一个专门的艺术风格识别专家。你的任务是分析用户提供的图像描述或风格需求，并识别出基本的艺术风格特征。请遵循以下步骤：

1. 仔细阅读用户输入，提取关键词和概念。
2. 基于这些信息，识别主要的艺术风格（如印象派、抽象主义、浪漫主义等）。
3. 列出该风格的3-5个最显著的基本特征。
4. 提供一个简短的总结，概括这个风格的整体感觉和氛围。

请以简洁、专业的方式呈现你的分析结果。你的输出将作为下一阶段风格细节分析的基础。

用户输入：{input}"

s1t2: &s1t2 "你是一个精通艺术风格细节的专家。你的任务是基于前一阶段识别出的基本风格特征，进一步扩充和详细描述具体的风格元素。同时也希望你完善前一阶段的不足。请按照以下步骤进行：

1. 仔细阅读LLM1提供的风格识别结果。
2. 对于每个提到的基本特征，提供2-3个更具体的表现形式或技巧。
3. 描述这个风格常用的色彩方案、笔触技巧、构图原则等。
4. 列举2-3位代表性艺术家的作品特点。
5. 提供一些可能在这种风格中出现的具体视觉元素或主题。

请以结构化的方式呈现你的分析，使其易于理解和转化为具体的图像描述。你的输出将用于下一阶段的风格语言转换。

LLM1的输出：{input}"

s1t3: &s1t3 "你是一个专门的文生图提示词专家。你的任务是将前两个阶段提供的艺术风格特征和细节转化为适合文生图模型使用的描述语言。同时也希望你完善前一阶段的不足。请遵循以下指南：

1. 仔细阅读LLM2提供的风格分析和细节。
2. 将这些信息转化为简洁、具体且富有描述性的短语。
3. 使用文生图模型常用的关键词和格式，如特定的标点符号、权重标记等。
4. 包含颜色、构图、光影、质地等方面的详细描述。
5. 添加一些技术性词汇，如渲染方式、艺术媒介等。
6. 确保使用的语言和术语是文生图模型能够理解和处理的。

你的输出应该是一系列强大、精确的提示词，这些词能够指导文生图模型生成符合特定艺术风格的图像。

LLM2的输出：{input}"

s1t4: &s1t4 "你是一个专门负责确保艺术风格描述一致性和连贯性的专家。你的任务是审查并优化前一阶段生成的文生图提示词，确保它们能够产生风格统一、协调的图像。请按照以下步骤进行：

1. 仔细阅读LLM3提供的文生图提示词。
2. 检查所有元素是否与最初识别的艺术风格保持一致。
3. 确保各个描述之间没有矛盾或冲突。
4. 调整词语顺序，使整体描述更加流畅和有逻辑。
5. 如果需要，添加转换词或短语来增强连贯性。
6. 确保关键风格元素得到适当的强调和权重。
7. 移除任何可能导致风格偏离的不必要或矛盾的描述。
8. 最后，提供一个简洁的总结，概括整体风格和预期的视觉效果。

你的输出应该是一个经过优化、高度连贯且风格一致的文生图提示词集合，可以直接用于生成符合预期艺术风格的图像。

LLM3的输出：{input}"


# style 2 构图
s2t1: &s2t1 "作为一位专业的构图分析专家，你的任务是识别和定义给定描述中的基本构图布局。请关注以下几点：
1. 识别可能使用的经典构图技巧（如黄金分割、三分法、对角线构图等）
2. 分析画面的整体平衡和对称性
3. 确定画面的主要分割线或区域
4. 考虑画面的纵横比及其对构图的影响

请用简洁明了的语言描述你的分析结果，重点突出构图的关键特征。你的输出将用于进一步的元素排布分析。
用户输入：{input}"

s2t2: &s2t2 "基于前一阶段的布局分析，你的任务是详细描述主要元素在画面中的位置和关系。同时也希望你完善前一阶段的不足。请注意以下几点：
1. 识别画面中的主要元素和次要元素
2. 描述每个重要元素的大致位置（使用如'上方'、'左下角'等描述）
3. 分析元素之间的空间关系和比例
4. 考虑元素排布如何强化或利用了基本构图布局

请用清晰、具体的语言描述元素的排布，为下一阶段的构图动态分析做准备。

LLM1的输出：{input}"

s2t3: &s2t3 "根据之前的布局和元素排布分析，你的任务是分析画面的视觉流动和重心分布。同时也希望你完善前一阶段的不足。请关注以下方面：
1. 确定画面的视觉路径，描述观者的视线可能如何在画面中移动
2. 分析画面的重心位置及其对整体平衡的影响
3. 识别可能存在的视觉张力或动态元素
4. 考虑构图如何引导观者的注意力

请用生动的语言描述画面的视觉动态，突出构图如何创造运动感和引导视线。你的分析将用于最终的构图优化。

LLM2的输出：{input}"

s2t4: &s2t4 "基于前三个阶段的分析，你的任务是整合所有信息，并优化构图描述以适应文生图模型。请遵循以下指导：
1. 综合前面的分析，提炼出最关键的构图特征
2. 使用文生图模型易于理解的明确、具体的语言重新描述构图
3. 确保描述中包含布局、元素排布和视觉动态的关键信息
4. 添加可能有助于文生图模型更好理解和执行的具体细节或例子
5. 确保关键元素得到适当的强调和权重。
6. 保持描述的简洁性和清晰度，避免过于复杂或模糊的表述

你的输出应该是一个优化的、全面的构图描述，直接可用于指导文生图模型生成图像。

LLM3的输出：{input}"


# style 3 视觉中心
s3t1: &s3t1 "作为一个专门的图像焦点识别专家，你的任务是确定画面的主要视觉焦点。请仔细分析给定的图像描述，并完成以下任务：

1. 识别画面中最引人注目的元素或区域。
2. 解释为什么这些元素或区域会成为视觉焦点（如大小、位置、颜色对比等）。
3. 如果存在多个焦点，请按重要性排序并解释它们之间的关系。
4. 考虑画面的整体构图，评估焦点的位置是否符合构图原则（如黄金分割、三分法则等）。

请以简洁明了的方式描述你的发现，为下一阶段的分析提供清晰的基础。

用户输入：{input}"

s3t2: &s3t2 "作为视觉焦点强化专家，你的任务是分析如何增强已识别的视觉中心。同时也希望你完善前一阶段的不足。基于上一个LLM的输出，请完成以下任务：

1. 对于每个已识别的焦点，提出具体的强化建议，包括但不限于：
a. 光线处理（如聚光、阴影等）
b. 细节增强（如锐化、纹理等）
c. 色彩对比（如饱和度、明度等）
d. 周围环境处理（如模糊背景、引导线等）

2. 解释每个强化技巧如何有助于突出视觉焦点。
3. 考虑这些强化技巧之间的平衡，确保它们协同工作而不会相互干扰。
4. 如果有多个焦点，讨论如何通过这些技巧来建立视觉层次。

请以结构化的方式呈现你的建议，为下一阶段的视线引导提供明确的指导。

LLM1的输出：{input}"

s3t3: &s3t3 "作为视线引导专家，你的任务是设计如何引导观者的视线到已识别和强化的焦点。同时也希望你完善前一阶段的不足。基于前两个LLM的输出，请完成以下任务：

1. 分析画面的整体布局，确定最佳的视线路径。
2. 提出具体的视线引导技巧，例如：
a. 线条和形状的使用
b. 色彩和亮度的渐变
c. 物体或人物的朝向
d. 重复元素或图案
e. 负空间的利用

3. 解释每个引导技巧如何与已识别的焦点和强化方法协同工作。
4. 如果有多个焦点，描述如何创建一个视觉叙事，引导观者按特定顺序浏览这些焦点。
5. 考虑如何平衡引导性和自然感，避免过于刻意或人为的感觉。

请以清晰、逻辑化的方式描述你的视线引导策略，为最终的视觉中心整合提供全面的指导。

LLM2的输出：{input}"

s3t4: &s3t4 "作为视觉中心整合专家，你的任务是综合前三个LLM的输出，创建一个优化的、全面的视觉中心描述，并将其转化为适合文生图模型的语言。请完成以下任务：

1. 仔细审阅前三个LLM的输出，包括焦点识别、焦点强化和视线引导的建议。

2. 整合这些信息，创建一个连贯的视觉中心描述，包括：
a. 主要焦点的位置和特征
b. 焦点强化的具体方法
c. 视线引导的策略和技巧

3. 确保描述中的各个元素相互协调，创造出和谐统一的视觉效果。

4. 将整合后的描述转化为适合文生图模型的明确、具体的指令，考虑以下方面：
a. 使用文生图模型常用的关键词和术语
b. 描述的具体性和可操作性
c. 避免模糊或主观的表述

5. 对整合后的描述进行一次最终的优化，确保：
a. 描述的完整性和一致性
b. 与整体画面构图的协调
c. 艺术效果和技术可行性的平衡

6. 确保关键元素得到适当的强调和权重。
7. 提供一个简洁的总结，概括视觉中心设计的核心理念和预期效果。

请以结构化、易于理解的格式呈现你的最终输出，确保它能直接用于指导文生图模型生成高质量、视觉中心明确的图像。

LLM3的输出：{input}" 


# style 4 色调
s4t1: &s4t1 "你是一个专门的色彩基调分析专家。你的任务是确定图像的整体色彩氛围和主色调。请遵循以下步骤：
1. 仔细阅读用户提供的图像描述或色彩需求。
2. 基于这些信息，确定2-3个可能的整体色彩基调选项。
3. 对每个选项，明确指出主色调和次要色调。
4. 简要描述每个色彩基调如何影响整体氛围。
请以简洁、专业的方式呈现你的分析结果。你的输出将作为下一阶段色彩关系分析的基础。

用户输入：{input}"

s4t2: &s4t2 "你是一个精通色彩关系的专家。你的任务是分析由前一阶段提供的色彩基调选项，并深入探讨色彩之间的和谐、对比和过渡关系。同时也希望你完善前一阶段的不足。请按照以下步骤进行：
1. 仔细阅读LLM1提供的色彩基调选项。
2. 对每个选项，分析主要颜色之间的和谐度。
3. 描述可能的色彩对比效果。
4. 解释色彩之间的过渡方式。
5. 提供具体建议，如何通过调整色彩关系来增强整体视觉效果。
请以结构化的方式呈现你的分析，使其易于理解和应用。你的输出将用于下一阶段的色彩情感分析。

LLM1的输出：{input}"

s4t3: &s4t3 "你是一个专注于色彩心理学的专家。你的任务是探讨色彩选择对画面情感的影响。同时也希望你完善前一阶段的不足。请按照以下步骤进行：
1. 仔细阅读前两个阶段提供的色彩分析。
2. 对每种色彩方案，分析其可能引发的主要情感反应。
3. 解释这些色彩如何影响画面的整体情绪和氛围。
4. 讨论色彩组合可能传达的潜在象征意义。
5. 提供建议，如何通过微调色彩来强化或改变特定情感效果。
请以清晰、富有洞察力的方式呈现你的分析。你的输出将用于最终的色彩描述优化。

LLM2的输出：{input}"

s4t4: &s4t4 "你是一个专门的文本优化专家，精通将复杂的色彩分析转化为适合文生图模型的语言。你的任务是整合前几个阶段的所有色彩分析，并将其转化为简洁、精确、易于理解的描述。请按照以下步骤进行：
1. 仔细阅读前三个阶段提供的所有色彩分析。
2. 提取最关键、最有影响力的色彩信息。
3. 使用文生图模型常用的词汇和表达方式重新组织这些信息。
4. 创建一个简洁但详细的色彩描述，包括主色调、色彩关系和情感效果。
5. 确保描述中包含具体的色彩名称、强度和分布信息。
6. 确保关键元素得到适当的强调和权重。
7. 添加一些可能有助于图像生成的修饰词或短语。
请以清晰、简洁且易于文生图模型理解的方式呈现你的最终描述。你的输出将直接用于图像生成过程。

LLM3的输出：{input}" 

summary: &summary "你是专业的视觉艺术描述专家。你的任务是将给定的视觉元素描述转化为连贯且详尽的图像提示，适用于如Stable Diffusion 3这样的AI图像生成模型。

请仔细分析以下输入：

艺术风格：{artistic_style}

构图：{composition}

视觉中心：{visual_center}

色调：{color_tone}

基于这些信息，创建一个全面的图像描述。你的描述应该：

1.清楚地描述场景中的主要视觉元素及其位置。
2.解释这些元素是如何根据给定的构图安排的。
3.详细描述整体的色调和氛围。
4.融入特定的艺术风格元素。
5.使用丰富的、具体的形容词来增强描述的视觉效果。
6.确保描述中所有元素和谐统一。
7.使用适合AI图像生成的语言和术语。

请提供一个连贯的描述，确保它可以被Stable Diffusion 3直接用作高质量的图像生成提示。"



styles:
  -
    name: 'artistic_style'
    template:
      - *s1t1
      - *s1t2
      - *s1t3
      - *s1t4
  -
    name: 'composition'
    template:
      - *s2t1
      - *s2t2
      - *s2t3
      - *s2t4
  -
    name: 'visual_center'
    template:
      - *s3t1
      - *s3t2
      - *s3t3
      - *s3t4
  -
    name: 'color_tone'
    template:
      - *s4t1
      - *s4t2
      - *s4t3
      - *s4t4

openai_api_set:
  api_key: f2oFPKXs3EW0eJh7fhfBCTLRZtWOMym5i1vMfm7e5ENmk1DI
  base_url: https://api.f2gpt.com/v1
  model: gpt-4-turbo

ollama_api_set:
  host: '127.0.0.1'
  port: '11434'
  model: 'llama3.1:8b' # qwen2:7b, llama3.1:8b, llama3.1-8b-instruct-dpo-zh
  temperature: 0

api_in_use: 'ollama' # ollama, openai

sys_ins: 你是一个AI助手，你要完成用户给你的所有指令，不允许有差错